---

- name: install and configure httpd
  hosts: webserver
  remote_user: user
  become: yes

  vars:
    http_port: 80

  tasks:
  - name: install httpd
    yum: name=httpd state=latest

  - name: create httpd configuration file
    template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
    notify: restart httpd

  - name: create httpd log file
    file: path=/var/log/httpd.log state=touch owner=root group=wheel mode=0775

  - name: start httpd service
    service: name=httpd state=started enabled=yes

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
